### ISSUE TITLE
Erro in light

### ISSUE THREAD

**Issue by LendaUrbana** [Galileo88/SSRSSContinued#2]
There was a problem using the mod with the lights in the game. Follow the link of the problem screen with and without the mod

https://imgur.com/a/FZIEx

**Comment by acidpaintball** [comment]
I have the same issue with crafts and buildings.
windows 10 with NVidia 1060

**Comment by acidpaintball** [comment]
I was testing with removing different config files and found if I remove "SunCurve.cfg."
Everything within this file I'm at a loss.. I'm not a dev.

**Comment by Galileo88** [comment]
I’ll fix it whenever I get around to it. I know what the issue is

**Comment by acidpaintball** [comment]
Thank you, Galileo.
BTW I love your mods.  It brings an all new adventure to the game.
