### ISSUE TITLE
Wrong path in release 0.0.3.1

### ISSUE THREAD

**Issue by n-wizard** [Galileo88/SSRSSContinued#3]
Error loading Sun flares:
[Scatterer] Custom sunflare cannot be added to Sun System.IO.IsolatedStorage.IsolatedStorageException: Could not find a part of the path "<skip>/GameData/SSRSS/visuals/scatterer/SunFlares/Sun/sunSpikes.png"

Release 0.0.3.1 ZIP file path is: /GameData/SSRSS/visuals/scatterer/Sunflares/
sould be: /GameData/SSRSS/visuals/scatterer/SunFlares/

**Comment by Galileo88** [comment]
No, my cfgs are correct. I have no idea what you are talking about. closing this report.
